cmsadmin/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.cmsadmin, name="cms-admin")
]

resources/forms.py
from django import forms
from django.utils.safestring import mark_safe
from .utils import msgs, language_code
from .models import Resources, ResourceTypes, ResourceStatuses, Langs, Authors


class SuggestResourceForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        msgs = kwargs.pop('msgs')
        super().__init__(*args, **kwargs)
        self.msgs = msgs
        self.language_code = msgs['language_code']

        self.fields['title'].label = msgs['suggest_title']
        self.fields['title'].error_messages = {'required': msgs['suggest_title'] + ' ' + msgs['error_required']}

        self.fields['subtitle'].label = msgs['suggest_subtitle']

        self.fields['type'].label = msgs['resource_type']
        self.fields['type'].error_messages = {'required': msgs['resource_type'] + ' ' + msgs['error_required']}
        self.fields['type'].queryset = ResourceTypes.objects.filter(lang_id=self.language_code)

        self.fields['description'].label = msgs['suggest_desc']
        self.fields['description'].error_messages = {'required': msgs['suggest_desc'] + ' ' + msgs['error_required']}

        self.fields['resource_link'].label = msgs['link']
        self.fields['group_link'].label = msgs['group_link']
        self.fields['date_created'].label = msgs['resourcecreated']
        self.fields['suggested_authors'].label = msgs['suggested_authors']
        self.fields['suggested_editors'].label = msgs['suggested_editors']
        self.fields['submitter_name'].label = msgs['submitter_name']
        self.fields['submitter_email'].label = msgs['submitter_email']
        self.fields['book'].label = msgs['book_name_for_chapter']
        self.fields['isbn'].label = 'ISBN'
        self.fields['journal'].label = msgs['journal_name']
        self.fields['journal_issue'].label = msgs['journal_issue']

    title = forms.CharField(label=msgs['suggest_title'],
                            max_length=255,
                            help_text="255 characters max.",
                            error_messages={"required": msgs['error_required'],
                                            "max_length": msgs['error_max_chars']})  # 255

    subtitle = forms.CharField(label=msgs['suggest_subtitle'],
                               required=False,
                               max_length=500,
                               help_text="500 characters max.",
                               error_messages={"max_length": msgs['error_max_chars']})  # 500

    type = forms.ModelChoiceField(queryset=ResourceTypes.objects.filter(lang_id=language_code),
                                  label=msgs['resource_type'],
                                  error_messages={'required': msgs['error_required']},
                                  widget=forms.Select(attrs={'onchange': 'toggleFields(this);'}),
                                  to_field_name='resource_type_id')

    description = forms.CharField(label=msgs['suggest_desc'], widget=forms.Textarea,
                                  max_length=1000,
                                  error_messages={"required": msgs['error_required'],
                                                  "max_length": msgs['error_max_chars']})  # 1000

    submitter_comments = forms.CharField(label=msgs['submitter_comments'], required=False, widget=forms.Textarea,
                                         max_length=1000)

    class Meta():
        def __init__(self, outer_instance):
            self.outer_instance = outer_instance
            self.msgs = outer_instance.msgs

        model = Resources
        fields = ['title', 'subtitle', 'description',
                  'type',
                  'book', 'isbn', 'journal', 'journal_issue',
                  'suggested_authors', 'suggested_editors',
                  'resource_link',
                  'group_link',
                  'date_created',
                  'submitter_name', 'submitter_email', 'submitter_comments']
        labels = {
            'resource_link': msgs['link'],
            'group_link': msgs['group_link'],
            'date_created': msgs['resourcecreated'],
            'suggested_authors': msgs['suggested_authors'],
            'suggested_editors': msgs['suggested_editors'],
            'submitter_name': msgs['submitter_name'],
            'submitter_email': msgs['submitter_email'],
            'book': msgs['book_name_for_chapter'],
            'isbn': 'ISBN',
            'journal': msgs['journal_name'],
            'journal_issue': msgs['journal_issue']
        }


class ReviewSuggestedResource(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        msgs = kwargs.pop('msgs')
        langs = kwargs.pop('langs')

        if 'instance' in kwargs:
            resource_instance = kwargs.pop('instance', None)

        super().__init__(*args, **kwargs)

        self.msgs = msgs
        self.language_code = msgs['language_code']
        self.langs = langs

    title = forms.CharField(label=msgs['suggest_title'],
                            max_length=255,
                            help_text="255 characters max.",
                            error_messages={"required": msgs['suggest_title'] + ' ' + msgs['error_required'],
                                            "max_length": msgs['error_max_chars']})  # 255

    subtitle = forms.CharField(label=msgs['suggest_subtitle'],
                               required=False,
                               max_length=500,
                               help_text="500 characters max.",
                               error_messages={"max_length": msgs['error_max_chars']})  # 500

    type = forms.ModelChoiceField(queryset=ResourceTypes.objects.filter(lang_id=language_code),
                                  label=msgs['resource_type'],
                                  error_messages={'required': msgs['resource_type'] + ' ' + msgs['error_required']},
                                  widget=forms.Select(attrs={'onchange': 'toggleFields(this);'}),
                                  to_field_name='resource_type_id')

    lang = forms.ModelChoiceField(queryset=Langs.objects.all(),
                                  label=msgs['lang'],
                                  error_messages={'required': msgs['lang'] + ' ' + msgs['error_required']},
                                  to_field_name='id')

    description = forms.CharField(label=msgs['suggest_desc'], widget=forms.Textarea,
                                  max_length=1000,
                                  error_messages={"required": msgs['suggest_desc'] + ' ' + msgs['error_required'],
                                                  "max_length": msgs['error_max_chars']})  # 1000

    submitter_comments = forms.CharField(label=msgs['submitter_comments'], required=False, widget=forms.Textarea,
                                         max_length=1000)

    resource_status = forms.ModelChoiceField(queryset=ResourceStatuses.objects.all(),
                                             label='STATUS',
                                             initial=ResourceStatuses.objects.get(pk=1),
                                             widget=forms.Select(),
                                             to_field_name='id')

    authors = forms.ModelMultipleChoiceField(
        queryset=Authors.objects.all(),
        label=mark_safe('Select Author(s)<br><i>Use [Shift] to select more than one. Select ----- for no author</i>'),
        required=False,
        widget=forms.SelectMultiple(attrs={'class': 'form-control authors-multiselect'}),
    )

    editors = forms.ModelMultipleChoiceField(
        queryset=Authors.objects.all(),
        label=mark_safe('Select Editor(s)<br><i>Use [Shift] to select more than one. Select ----- for no editors</i>'),
        required=False,
        widget=forms.SelectMultiple(attrs={'class': 'form-control authors-multiselect'}),
    )

    resource_file = forms.FileField(
        allow_empty_file=True,
        label='File',
        required=False
    )

    img = forms.ImageField(
        allow_empty_file=True,
        label='Resource image',
        required=False
    )

    class Meta:

        def __init__(self, outer_instance):
            self.outer_instance = outer_instance
            self.msgs = outer_instance.msgs

        model = Resources
        fields = ['resource_status', 'slug',
                  'title', 'subtitle', 'description',
                  'type', 'lang',
                  'book', 'isbn', 'journal', 'journal_issue',
                  'suggested_authors', 'authors',
                  'suggested_editors', 'editors',
                  'resource_link',
                  'group_link',
                  'date_created',
                  'submitter_name', 'submitter_email', 'submitter_comments',
                  'resource_file', 'img'
                  ]
        labels = {
            'resource_link': msgs['link'],
            'group_link': msgs['group_link'],
            'date_created': msgs['resourcecreated'],
            'suggested_authors': msgs['suggested_authors'],
            'suggested_editors': msgs['suggested_editors'],
            'submitter_name': msgs['submitter_name'],
            'submitter_email': msgs['submitter_email'],
            'book': msgs['book_name_for_chapter'],
            'isbn': 'ISBN',
            'journal': msgs['journal_name'],
            'journal_issue': msgs['journal_issue']
        }

resources/templates/resources/all-resources.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{msgs.allresources}}
{% endblock %}

{% block css_files %}
    <link rel="stylesheet" href="{% static "resources/index.css" %}" />
{% endblock %}

{% block content %}

<section id="all-resoruces">
    <h2 style="margin-left:10px">{{ msgs.allresources }}</h2>
    <div class="grid-container">
        {% for r in resources %}
            {% include "resources/includes/item.html" %}
        {% endfor %}
    </div>
</section>

{% endblock %}

resources/templates/resources/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Decolonization Resources
{% endblock %}

{% block css_files %}
    <link rel="stylesheet" href="{% static "resources/index.css" %}" />
{% endblock %}

{% block content %}

    <section id="welcome">
        <header>
            <div class="left-section">
                <img src="{% static 'resources/images/decolru.png' %}" alt="Russian Colonialism - Resource Library" />
            </div>
            <div class="right-section">
                <h1>{{ msgs.libtitle }}</h1>
                <p>{{ msgs.welcome }}</p>
            </div>
        </header>
    </section>

    <section id="latest" style="margin:10px">
        <h2>{{ msgs.recentadditions }}</h2>
        <div class="grid-container">
            {% for r in resources %}
                {% include "resources/includes/item.html" %}
            {% endfor %}
        </div>

    </section>

    <section id="bottom" style="margin:10px">
        <h2>What it's all about?</h2>
        <p>
            This is a library of resources on Russian colonialism.
        </p>
    </section>

{% endblock %}

resources/templates/resources/resource-details.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ r.title }}
{% endblock %}

{% block css_files %}
    <link rel="stylesheet" href="{% static "resources/resource-details.css" %}" />
{% endblock %}

{% block content %}

<section id="summary">
    <article>
        {% if r.img_file %}
            <img src="{% static 'resources/images/'|add:r.img_file %}" alt="{{ r.title }}">
        {% endif %}
        <h2>{{ r.title }}</h2>
        {% if r.subtitle %}
            <h3>{{ r.subtitle }}</h3>
        {% endif %}
        {% if r.authors_full_name_lat %}
            <p>
                {{ r.authors_full_name_lat }}
            </p>
        {% endif %}
        {% if r.editors_full_name_lat %}
            <p>
                {{ r.editors_full_name_lat }}&nbsp;({{ msgs.suggested_editors }})
            </p>
        {% endif %}
        {% if r.lang.lang_name %}
            <p>
                {{ msgs.lang }}:&nbsp;{{ r.lang.lang_name }}
            </p>
        {% endif %}
        <p><i>{{ type }}</i></p>
        {% if r.isbn %}
        <p>ISBN:&nbsp;{{ r.isbn }}</p>
        {%  endif %}
        <p>{{ msgs.resourcecreated}}: <time>{{ r.date_created }}</time></p>
        <p>{{ msgs.addedtolib}}: <time>{{ r.date_added_to_lib }}</time></p>
        {% if r.resource_link %}
        <a href="{{ r.resource_link }}" target="_blank">{{ r.resource_link }}</a>
        {% endif %}


        <p>{{ r.tags }}</p>
    </article>
</section>

{% if r.description %}
    <main>
        <p>{{ r.description|linebreaks }}</p>
    </main>
{% endif %}
<br>&nbsp;<br>&nbsp;<br>
{% endblock %}

resources/templates/resources/review-suggestions.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Review Suggestions
{% endblock %}

{% block css_files %}
    <link rel="stylesheet" href='{% static "resources/suggest-resource.css" %}' />
{% endblock %}

{% block content %}
<div class="container">
  <div class="title">
      <div>
        <img src="{% static 'resources/images/'|add:'leone.png'' %}" alt="Venetian lion" height="75" style="margin-left:0.25rem">
      </div>
      <div>
          <h1 id="review_title" style="margin-left:1rem;margin-right:1rem;font-size:4rem;font-weight:lighter;color:074958;padding-bottom:0.5rem">Review Suggestions</h1>
      </div>
      <div id="status" style="margin-left: auto;padding-right:2rem">
          <label for="select_status" style="float: left;">Filter by status:</label>
          <select id="select_status" name="select_status" style="float: left;">
            {% for status in all_statuses %}
                <option value="{{ status.id }}">{{ status.description }}</option>
            {% endfor %}
          </select>
      </div>
  </div>
  <div class="content-container">
      <div id="suggestions-list" class="sidebar">
        <button id="add_resource" style="width:100%" onclick="addNewResource()">ADD NEW RESOURCE</button>
        <ul id="suggestions-ul">
        </ul>
      </div>
      <div class="main">
          <form id="reviewForm" name="reviewForm" method="POST" enctype="multipart/form-data" novalidate style="text-align:right;margin-bottom:1.5rem">
              {% csrf_token %}
              <table style="width:100%;borders:none;margin-bottom:1rem">
                  <tr>
                      <td id="new_resource_heading" style="width:75%;text-align:left;color:#ac0d00;font-weight:bold;font-size:1.5rem">
                          NEW RESOURCE
                      </td>
                      <td>
                          <button id="btnSubmitReviewTop" type="submit">SAVE</button>
                      </td>
                  </tr>
              </table>
              <input type="hidden" id="id_id" name="id" value="">
              <div class="form-control {% if form.title.errors %}errors{% endif %}">
                <div class="label-container">
                    Submitted on:&nbsp;
                </div>
                <div class="field-container">
                    <input type="text" id="id_date_submitted" name="date_submitted">
                </div>
              </div>

              {% for field in form %}
                <div class="form-control {% if form.title.errors %}errors{% endif %}">
                    <div class="label-container">
                        {{ field.label_tag }}&nbsp;
                    </div>
                    <div class="field-container">
                        {{ field.errors}}
                        {{ field }}
                    </div>
                </div>
              {% endfor %}
              <br>
              <button id="btnSubmitReviewBottom" type="submit">SAVE</button>
          </form>
      </div>
  </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        const suggestionsUl = document.getElementById("suggestions-ul");
        const suggestions_json = JSON.parse('{{ suggestions_json|escapejs }}');

        //Prepend asterisk to required fields' labels
        prependAsteriskToRequiredFieldLabels();

        // Iterate over suggestions_json and create list items
        suggestions_json.forEach(suggestion => {
            const li = document.createElement("li");
            li.setAttribute("data-id", suggestion.id);
            li.textContent = suggestion.title;
            suggestionsUl.appendChild(li);

            // Add click event listener to each list item
            li.addEventListener("click", function() {
                const suggestionId = parseInt(this.dataset.id);
                const selectedSuggestion = suggestions_json.find(s => s.id === suggestionId);

                // load the selected suggestion into the form
                loadSuggestionIntoForm(selectedSuggestion);
            });
        });

        //load first suggestion into the form
        if (suggestions_json.length > 0) {
            loadSuggestionIntoForm(suggestions_json[0]);
        }

        const selectStatus = document.getElementById("select_status");

        // Add event listener to detect changes in the select element
        selectStatus.addEventListener("change", function() {
            const selectedStatusId = this.value; // Get the selected status_id

            // Reload the page with the selected status_id as a query parameter
            window.location.href = window.location.pathname + "?status_id=" + selectedStatusId;
        });

        //Set the value of filter-by-status select
        const urlParams = new URLSearchParams(window.location.search); // Get the value of the 'status_id' query parameter from the URL
        if(urlParams=='')
            urlParams = 1;
        const statusId = urlParams.get('status_id');
        const selectFilterByStatus = $('#select_status');
        selectFilterByStatus.val(statusId);

        const selectedOptionText = selectFilterByStatus.find('option:selected').text();
        $('#review_title').text('Review ' + selectedOptionText);

    });

    // add event listener to the review form submit button (top)
    document.getElementById("btnSubmitReviewTop").addEventListener("click", function(event) {
        validateFormSubmission(event, 'reviewForm');
    });

    // add event listener to the review form submit button (bottom)
    document.getElementById("btnSubmitReviewBottom").addEventListener("click", function(event) {
        validateFormSubmission(event, 'reviewForm');
    });

    // load suggestion into the review form
    function loadSuggestionIntoForm(s) {

        document.getElementById('new_resource_heading').innerHTML = "";

        //Do not load data into these fields
        const excludedFields = ['img_file', 'date_added_to_lib'];

        //Specify fields for removing trailing _id
        remove_id = {'resource_status_id':'resource_status', 'type_id':'type', 'lang_id':'lang'}

        for (const key in s) {
            if(!excludedFields.includes(key)) {
                try {
                    //remove trailing id if needed
                    if (key in remove_id) {
                        eid = "id_" + remove_id[key];
                    } else {
                        eid = "id_" + key;
                    }

                    const element = document.getElementById(eid);
                    if (element) {
                        switch(key) {
                            case 'authors':
                            case 'editors':
                                const selectedOptions = [];

                                // Clear existing selections
                                Array.from(element.options).forEach(option => {option.selected = false;});
                                // Set selected authors based on suggestion data
                                const authorIds = s[key];
                                authorIds.forEach(authorId => {
                                    const option = element.querySelector(`option[value='${authorId}']`);
                                    if (option) {
                                        option.selected = true;
                                        selectedOptions.push(option);
                                    }
                                });

                                // Move selected options to the top of the select
                                selectedOptions.forEach(option => {
                                    element.removeChild(option); // Remove option from its current position
                                    element.insertBefore(option, element.firstChild); // Insert option at the beginning of the select element
                                });
                                break;
                            case 'resource_file':
                            case 'img':
                                if(s[key]) {
                                    const baseURL = window.location.origin;
                                    const currUrl = "<a href='" + baseURL + "/media/" + s[key] + "' target=_blank>Current file</a>"
                                    element.insertAdjacentHTML("beforebegin", currUrl);
                                }
                                break;
                            default:
                                setValue(element, s[key]);
                        }
                    } else {
                        console.error('Failed to find element [' + eid +']');
                    }
                } catch (error) {
                    console.error('Error setting value for element [' + eid + ']: ' + error.message);
                }
            }
        }

    } //(loadSuggestionIntoForm)

</script>

{% endblock %}

resources/templates/resources/suggest-resource.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ msgs.suggest_form_title }}
{% endblock %}

{% block css_files %}
    <link rel="stylesheet" href='{% static "resources/suggest-resource.css" %}' />
{% endblock %}

{% block content %}
<h1>{{ msgs.suggest_form_title }}</h1>
<form id="submitSuggestionForm" method="POST" novalidate style="text-align:right">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-control {% if form.title.errors %}errors{% endif %}">
            <div class="label-container">
                {{ field.label_tag }}&nbsp;
            </div>
            <div class="field-container">
                {{ field.errors}}
                {{ field }}
            </div>
        </div>
    {% endfor %}
    <br>
    <button type="submit" id="btnSubmitSuggestionForm">{{ msgs.submit }}</button>
    <button type="button">{{ msgs.cancel }}</button>
</form>

<script>
    $('#id_book, label[for="id_book"]').closest('.form-control').hide();
    $('#id_isbn, label[for="id_isbn"]').closest('.form-control').hide();
    $('#id_journal, label[for="id_journal"]').closest('.form-control').hide();
    $('#id_journal_issue, label[for="id_journal_issue"]').closest('.form-control').hide();
    $('#id_resource_status').val("1");

    prependAsteriskToRequiredFieldLabels();

    document.getElementById("btnSubmitSuggestionForm").addEventListener("click", function(event) {
        validateFormSubmission(event, 'submitSuggestionForm');
    });

    //document.getElementById("btnSubmitReviewTop").addEventListener("click", function(event) {
    //    validateFormSubmission(event, 'reviewForm');
    //});

</script>

{% endblock %}

resources/templates/resources/thankyou.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ msgs.resource_thank_you_title }}
{% endblock %}

{% block css_files %}
    <link rel="stylesheet" href='{% static "resources/suggest-resource.css" %}' />
{% endblock %}

{% block content %}

<h1>{{ msgs.resource_thank_you_title }}</h1>
<p>{{ msgs.resource_thank_you_text }}</p>
<div style="width:100%;text-align:center;margin-top:5rem">
    <button id="new_resource" onclick="suggestNewResource()">{{ msgs.submit_another_resource }}</button>
</div>
{% endblock %}